### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MarcosFP97** [lcschv/Trec_eval_extension#2]
Hi, I am a TREC 2020 Health Misinformation participant and I am trying to re run your trec eval extension code. However, when I run your example code, I got a segmentation fault code error. The code that I am running is the following:

`./trec_eval -c -M 1000 -m nlre -R qrels_twoaspects samples/sanitytests/qrels_sample_twoaspects.txt samples/sanitytests/run_random.txt
`

After manually debugging the trec_eval.c file I found that the line producing this error is [this](https://github.com/lcschv/Trec_eval_extension/blob/5747f564ae7d0a31975ccdfc6cdc21c93a96435a/Trec_eval_extension/trec_eval.c#L352). I would appreciate any hep to solve this issue.
Marcos

**Comment by lcschv** [comment]
Hi Marcos,

I just ran the command you sent me and it runs properly in my side. 
"nlre                    all     0.7254"

Are you using the qrels_sample_twoaspects.txt and run_random.txt as it was when you cloned the repository or have you made changes to it?

If yes, try to recompile (just call Make).

If the problem persists, feel free to contact me again! 
Best,
Lucas

**Comment by MarcosFP97** [comment]
Hi Lucas, 
Thank you for quick response. Yes, I am using both files as cloned. 
Recompiling did not work for me...
Best,
Marcos

**Comment by MarcosFP97** [comment]
I have tested it in another computer and the same error came up. I don't know what is going wrong... Maybe I am missing some step: I am just cloning the repo, compiling with Make and making the test.
Best,
Marcos

**Comment by lcschv** [comment]
Can you try to use the absolute path instead of relative path to both files?

**Comment by MarcosFP97** [comment]
That did not work either...
Marcos

**Comment by MarcosFP97** [comment]
Hi again, 
I was thinking about this problem and the only thing that came to my mind is that there could be a problem with the gcc compiler version. This is the version that I am using:

```
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lcschv** [comment]
Hi, Marcos.

Are you able to run Trec_eval properly? The original, not the extended one.

Regarding the gcc version:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.

Best,
Lucas

**Comment by MarcosFP97** [comment]
Hi again Lucas, 
It was a gcc version issue! I downgraded gcc to your version, 4.8.5, and everything worked fine. 
Thank you very much for your kind help.
Best,
Marcos
